Pim\Component\Catalog\Model\Product:
    constraints:
        - Pim\Component\Catalog\Validator\Constraints\UniqueProduct:
            message: The same identifier is already set on another product
            entityClass: Pim\Component\Catalog\Model\AbstractProduct
    properties:
        identifier:
            - NotBlank: ~
            - Regex:
                pattern: '/^[^,;]+$/'
                message: 'regex.comma_or_semicolon.message'
            - Length:
                max: 255
    getters:
        values:
            - Symfony\Component\Validator\Constraints\Valid:
                traverse: true
