Pim\Component\Catalog\Model\Product:
#    group_sequence:
#        - Product
#        - api
#    constraints:
#        - Pim\Component\Catalog\Validator\Constraints\UniqueEntity:
#            entityClass: Pim\Component\Catalog\Model\AbstractProduct
#            groups: [Product]
    properties:
        identifier:
            - NotBlank: ~
            - Regex:
                pattern: '/^[^,;]+$/'
                message: 'regex.comma_or_semicolon.message'
            - Length:
                max: 255
    getters:
        values:
            - Symfony\Component\Validator\Constraints\Valid:
                traverse: true
