parameters:
    pim_enrich.doctrine.query.ascendant_categories.class: 'Pim\Bundle\EnrichBundle\Doctrine\ORM\Query\AscendantCategories'
    pim_enrich.doctrine.query.selected_for_mass_edit.class: Pim\Bundle\EnrichBundle\Doctrine\ORM\Query\SelectedForMassEdit

services:
    pim_enrich.doctrine.query.ascendant_categories:
        class: '%pim_enrich.doctrine.query.ascendant_categories.class%'
        arguments:
            - '@doctrine.orm.entity_manager'

    pim_enrich.doctrine.query.selected_for_mass_edit:
        class: '%pim_enrich.doctrine.query.selected_for_mass_edit.class%'
        arguments:
            - '@pim_enrich.query.product_and_product_model_query_builder_factory'
            - '@pim_catalog.query.product_query_builder_factory'
